TEAM_MAP = {
    "Atlanta Hawks": "ATL Hawks",
    "Hawks": "ATL Hawks",
    "Boston Celtics": "BOS Celtics",
    "Celtics": "BOS Celtics",
    "Brooklyn Nets": "BKN Nets",
    "Nets": "BKN Nets",
    "Charlotte Hornets": "CHA Hornets",
    "Hornets": "CHA Hornets",
    "Chicago Bulls": "CHI Bulls",
    "Bulls": "CHI Bulls",
    "Cleveland Cavaliers": "CLE Cavaliers",
    "Cavaliers": "CLE Cavaliers",
    "Dallas Mavericks": "DAL Mavericks",
    "Mavericks": "DAL Mavericks",
    "Denver Nuggets": "DEN Nuggets",
    "Nuggets": "DEN Nuggets",
    "Detroit Pistons": "DET Pistons",
    "Pistons": "DET Pistons",
    "Golden State Warriors": "GSW Warriors",
    "Warriors": "GSW Warriors",
    "GS Warriors": "GSW Warriors",
    "GSW": "GSW Warriors",
    "Houston Rockets": "HOU Rockets",
    "Rockets": "HOU Rockets",
    "Indiana Pacers": "IND Pacers",
    "Pacers": "IND Pacers",
    "Los Angeles Clippers": "LAC Clippers",
    "Clippers": "LAC Clippers",
    "LA Clippers": "LAC Clippers",
    "Los Angeles Lakers": "LAL Lakers",
    "Lakers": "LAL Lakers",
    "LA Lakers": "LAL Lakers",
    "Memphis Grizzlies": "MEM Grizzlies",
    "Grizzlies": "MEM Grizzlies",
    "Miami Heat": "MIA Heat",
    "Heat": "MIA Heat",
    "Milwaukee Bucks": "MIL Bucks",
    "Bucks": "MIL Bucks",
    "Minnesota Timberwolves": "MIN Timberwolves",
    "Timberwolves": "MIN Timberwolves",
    "New Orleans Pelicans": "NOP Pelicans",
    "Pelicans": "NOP Pelicans",
    "NO Pelicans": "NOP Pelicans",
    "NO": "NOP Pelicans",
    "New York Knicks": "NYK Knicks",
    "Knicks": "NYK Knicks",
    "Oklahoma City Thunder": "OKC Thunder",
    "Thunder": "OKC Thunder",
    "Orlando Magic": "ORL Magic",
    "Magic": "ORL Magic",
    "Philadelphia 76ers": "PHI 76ers",
    "76ers": "PHI 76ers",
    "Phoenix Suns": "PHX Suns",
    "Suns": "PHX Suns",
    "Portland Trail Blazers": "POR Trail Blazers",
    "Trail Blazers": "POR Trail Blazers",
    "Sacramento Kings": "SAC Kings",
    "Kings": "SAC Kings",
    "San Antonio Spurs": "SAS Spurs",
    "Spurs": "SAS Spurs",
    "SA Spurs": "SAS Spurs",
    "Toronto Raptors": "TOR Raptors",
    "Raptors": "TOR Raptors",
    "Utah Jazz": "UTA Jazz",
    "Jazz": "UTA Jazz",
    "Washington Wizards": "WAS Wizards",
    "Wizards": "WAS Wizards",
    "Atlanta Hawks ": "ATL Hawks",
    "Boston Celtics ": "BOS Celtics",
    "Brooklyn Nets ": "BKN Nets",
    "Charlotte Hornets ": "CHA Hornets",
    "Chicago Bulls ": "CHI Bulls",
    "Cleveland Cavaliers ": "CLE Cavaliers",
    "Dallas Mavericks ": "DAL Mavericks",
    "Denver Nuggets ": "DEN Nuggets",
    "Detroit Pistons ": "DET Pistons",
    "Golden State Warriors ": "GSW Warriors",
    "Houston Rockets ": "HOU Rockets",
    "Indiana Pacers ": "IND Pacers",
    "Los Angeles Clippers ": "LAC Clippers",
    "Los Angeles Lakers ": "LAL Lakers",
    "Memphis Grizzlies ": "MEM Grizzlies",
    "Miami Heat ": "MIA Heat",
    "Milwaukee Bucks ": "MIL Bucks",
    "Minnesota Timberwolves ": "MIN Timberwolves",
    "New Orleans Pelicans ": "NOP Pelicans",
    "New York Knicks ": "NYK Knicks",
    "NY Knicks": "NYK Knicks",
    "Oklahoma City Thunder ": "OKC Thunder",
    "Orlando Magic ": "ORL Magic",
    "Philadelphia 76ers ": "PHI 76ers",
    "Phoenix Suns ": "PHX Suns",
    "Portland Trail Blazers ": "POR Trail Blazers",
    "Sacramento Kings ": "SAC Kings",
    "San Antonio Spurs ": "SAS Spurs",
    "Toronto Raptors ": "TOR Raptors",
    "Utah Jazz ": "UTA Jazz",
    "Washington Wizards ": "WAS Wizards",
}

